version: '3.7'

services:
  laravel:
    build:
      context: ./
      dockerfile: Dockerfile
    # image: camilocastillo/laravel-app:v1.0.0
    container_name: laravel-app
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./public/:/var/www/html

